import type { Metadata } from "next";
import "./globals.css";
import Cursor from './components/CustomCursor'
import Navbar from './components/navbar'
import Footer from './components/footer'

export const metadata: Metadata = {
  title: "CQ Dev. Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Cursor/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
